[versions]
geyser = "2.7.0-SNAPSHOT"
sqlite = "3.49.1.0"
mysql = "9.2.0"
jackson = "2.15.2"

[libraries]
geyser-core = { group = "org.geysermc.geyser", name = "core", version.ref = "geyser" }
geyser-api = { group = "org.geysermc.geyser", name = "api", version.ref = "geyser" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }
mysql = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysql" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jackson-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson" }

[bundles]
geyser = [
    "geyser-core",
    "geyser-api"
]
